package UserInterface.Enterprise4.Organization1.WorkArea.Professor;

import TheBusiness.Business.Business;
import TheBusiness.EducationManagement.ProfessorProfile;
import TheBusiness.UserAccountManagement.UserAccount;
import UserInterface.Enterprise4.Organization1.WorkArea.Professor.WorkResp1.ManageCoursesJPanel;
import UserInterface.Main.ChangePasswordJPanel;
import javax.swing.JPanel;

/**
 * Represents the landing page for a Professor user in the Hospitality Ecosystem
 * Management System. Provides options to view courses offered and create new
 * courses. Displays relevant user information such as name, role, organization,
 * and enterprise.
 *
 * @author aadityakasbekar
 */
public class ProfessorLandingPageJPanel extends javax.swing.JPanel {

    Business business;
    ProfessorProfile professorProfile;
    javax.swing.JPanel CardSequencePanel;

    UserAccount userAcc;

    /**
     * Creates a new ProfessorLandingPageJPanel.
     *
     * @param b The Business object representing the back end system.
     * @param pp The ProfessorProfile associated with the logged-in professor.
     * @param clp The JPanel for card layout navigation.
     */
    public ProfessorLandingPageJPanel(Business b, ProfessorProfile pp, JPanel cardSequencePanel) {
        initComponents();
        this.business = b;
        this.professorProfile = pp;
        this.CardSequencePanel = cardSequencePanel;

        System.out.println("Welcome Professor");
        txtName.setText(this.professorProfile.getPerson().getName());
        txtRole.setText(this.professorProfile.getRole());

        txtOrganization.setText("Hospitality Training Institute1");

        txtEnterprise.setText("International Hotel School (IHS) Group");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblOrganization = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();
        lblEnterprise = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        btnViewCoursesOffered = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 300));
        setPreferredSize(new java.awt.Dimension(1000, 300));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome Professor");

        lblName.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblRole.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role:");

        txtRole.setEditable(false);
        txtRole.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblOrganization.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblOrganization.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganization.setText("Organization:");

        txtOrganization.setEditable(false);
        txtOrganization.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterprise.setText("Enterprise:");

        txtEnterprise.setEditable(false);
        txtEnterprise.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnViewCoursesOffered.setBackground(new java.awt.Color(0, 153, 255));
        btnViewCoursesOffered.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewCoursesOffered.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCoursesOffered.setText("Manage Courses Offered");
        btnViewCoursesOffered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoursesOfferedActionPerformed(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(0, 153, 255));
        btnChangePassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Change my password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChangePassword)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCoursesOffered)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrganization, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEnterprise, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRole)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(245, 245, 245))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEnterprise, txtName, txtOrganization, txtRole});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName))
                            .addGap(18, 18, 18)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblRole))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrganization)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterprise)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCoursesOffered)
                    .addComponent(btnChangePassword))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCoursesOfferedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoursesOfferedActionPerformed

        ManageCoursesJPanel manageCoursesJPanel = new ManageCoursesJPanel(business, professorProfile, CardSequencePanel);
        CardSequencePanel.add("ManageCourses", manageCoursesJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnViewCoursesOfferedActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:

        userAcc = business.getUserAccountDirectory().findUserAccount(professorProfile.getPerson().getPersonId());

        ChangePasswordJPanel changePasswordPanel = new ChangePasswordJPanel(business, userAcc);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ChangePasswordJPanel", changePasswordPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnViewCoursesOffered;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEnterprise;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables

}
