/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import TheBusiness.Personnel.EmployeeProfile;
import TheBusiness.Business.Business;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelManagerProfile;
import UserInterface.Enterprise3.Organization1.WorkArea.Customer.CustomerLandingPageJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sakshiwadaskar
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    Business business;
    javax.swing.JPanel CardSequencePanel;
    EmployeeProfile adminProfile;

    public AdminJPanel(Business b, EmployeeProfile hmp, JPanel cardSequencePanel) {
        initComponents();
        business = b;
        this.adminProfile = hmp;
        this.CardSequencePanel = cardSequencePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHS = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        btnBookings = new javax.swing.JButton();
        btnInstitute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHS.setBackground(new java.awt.Color(0, 153, 255));
        btnHS.setForeground(new java.awt.Color(255, 255, 255));
        btnHS.setText(" Hospitality Supplier (Ecolab Inc.)");
        btnHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHSActionPerformed(evt);
            }
        });
        add(btnHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 420, 50));

        btnHotel.setBackground(new java.awt.Color(0, 153, 255));
        btnHotel.setForeground(new java.awt.Color(255, 255, 255));
        btnHotel.setText(" Hotel Chain (Marriott International, Inc.)");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });
        add(btnHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 380, 50));

        btnBookings.setBackground(new java.awt.Color(0, 153, 255));
        btnBookings.setForeground(new java.awt.Color(255, 255, 255));
        btnBookings.setText("Online Booking Platform (Booking Holdings Inc.)");
        btnBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingsActionPerformed(evt);
            }
        });
        add(btnBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 380, 50));

        btnInstitute.setBackground(new java.awt.Color(0, 153, 255));
        btnInstitute.setForeground(new java.awt.Color(255, 255, 255));
        btnInstitute.setText(" Hospitality Training Institute (International Hotel School (IHS) Group)");
        btnInstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstituteActionPerformed(evt);
            }
        });
        add(btnInstitute, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gujarati MT", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO THE HOTEL MANAGEMENT SYSTEM!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myIcons/hotelImg2.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHSActionPerformed
        // TODO add your handling code here:
        ReportDashboardHotelSupplierJPanel supplierReportPanel = new ReportDashboardHotelSupplierJPanel(business, adminProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ReportDashboardHotelSupplierJPanel", supplierReportPanel);

        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnHSActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        // TODO add your handling code here:
        ReportDashboardHotelManagementJPanel hotelManagementReportPanel = new ReportDashboardHotelManagementJPanel(business, adminProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ReportDashboardHotelManagementJPanel", hotelManagementReportPanel);

        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnHotelActionPerformed

    private void btnBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingsActionPerformed
        ReportDashboardBookingsIncJPanel bookingsReportPanel = new ReportDashboardBookingsIncJPanel(business, adminProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ReportDashboardBookingsIncJPanel", bookingsReportPanel);

        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBookingsActionPerformed

    private void btnInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstituteActionPerformed
        ReportDashboardInstituteJPanel instituteReportPanel = new ReportDashboardInstituteJPanel(business, adminProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ReportDashboardInstituteJPanel", instituteReportPanel);

        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnInstituteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookings;
    private javax.swing.JButton btnHS;
    private javax.swing.JButton btnHotel;
    private javax.swing.JButton btnInstitute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
