/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import TheBusiness.Personnel.EmployeeProfile;
import TheBusiness.BookingManagement.Booking;
import TheBusiness.BookingManagement.Room;
import TheBusiness.Business.Business;
import TheBusiness.OrderManagement.Order;
import TheBusiness.OrderManagement.OrderItem;
import TheBusiness.ProductManagement.Product;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author sakshiwadaskar
 */
public class ReportDashboardHotelSupplierJPanel extends javax.swing.JPanel {

    Business business;
    javax.swing.JPanel CardSequencePanel;
    EmployeeProfile adminProfile;

    /**
     * Creates new form ReportDashboardJPanel
     */
    public ReportDashboardHotelSupplierJPanel(Business b, EmployeeProfile hmp, JPanel cardSequencePanel) {
        initComponents();
        business = b;
        this.adminProfile = hmp;
        this.CardSequencePanel = cardSequencePanel;
        showCharts();
        JButton button = new JButton();
        this.add(button);
        button.setLocation(new Point(10, 100));
        button.setText("Back");
    }

    private void showCharts() {

        //create dataset
        DefaultPieDataset barDatasetProductWiseData = new DefaultPieDataset();
        DefaultPieDataset barDatasetOrderedProducts = new DefaultPieDataset();

        ArrayList<Product> supplierCatalog = business.getHospitalitySupplierProductCatalog().getProductList();
        for (Product product : supplierCatalog) {
            barDatasetProductWiseData.setValue(product.getName(), product.getQuantity());
        }

        ArrayList<Order> hospitalityOrders = business.getHotelHospitalityOrders().getOrders();
        for (Order order : hospitalityOrders) {
            for (OrderItem oi : order.getOrderItems()) {
                barDatasetOrderedProducts.setValue(oi.getProduct().getName(), oi.getQuantity());
            }
        }

        JFreeChart productWisePieChart = ChartFactory.createPieChart("Hospitality Supplier Inventory", barDatasetProductWiseData, false, true, false);
        JFreeChart orderWisePieChart = ChartFactory.createPieChart("Top Selling Products", barDatasetOrderedProducts, false, true, false);

        PiePlot productWisePlot = (PiePlot) productWisePieChart.getPlot();
        PiePlot orderWisePlot = (PiePlot) orderWisePieChart.getPlot();

        //changing pie chart blocks colors
        orderWisePlot.setSectionPaint("Soap", new Color(255, 204, 102));
        orderWisePlot.setSectionPaint("Bedsheets", new Color(255, 255, 153));
        orderWisePlot.setSectionPaint("Shampoo", new Color(255, 255, 153));
        orderWisePlot.setSectionPaint("Towel Sets", new Color(255, 255, 179));

        productWisePlot.setSectionPaint("Soap", new Color(255, 204, 102));
        productWisePlot.setSectionPaint("Bedsheets", new Color(255, 255, 153));
        productWisePlot.setSectionPaint("Shampoo", new Color(255, 255, 153));
        productWisePlot.setSectionPaint("Towel Sets", new Color(255, 255, 179));

        orderWisePlot.setBackgroundPaint(Color.white);
        productWisePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)
        ChartPanel orderWiseChartPanel = new ChartPanel(orderWisePieChart);
        ChartPanel productWiseChartPanel = new ChartPanel(productWisePieChart);

        panelBarChart.removeAll();
        panelBarChart.add(orderWiseChartPanel, BorderLayout.CENTER);
        panelBarChart.add(productWiseChartPanel, BorderLayout.AFTER_LAST_LINE);
        panelBarChart.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        panelBarChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(panelBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(panelBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 302, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        AdminJPanel manageSuppliesPanel = new AdminJPanel(business, adminProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ManageSuppliesJPanel", manageSuppliesPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
