/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Enterprise1.Organization1.WorkArea.FrontDeskStaff.WorkResp2;

import TheBusiness.BookingManagement.Booking;
import TheBusiness.BookingManagement.Room;
import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.Personnel.Enterprise1.Organization1.FrontDeskStaffProfile;
import TheBusiness.Personnel.Person;
import TheBusiness.Personnel.Profile;
import TheBusiness.UserAccountManagement.UserAccount;
import UserInterface.Enterprise1.Organization1.WorkArea.FrontDeskStaff.FrontDeskStaffLandingPageJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aadityakasbekar
 */
public class BookARoomAtHotelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookARoomJPanel
     */
    Business business;
    javax.swing.JPanel CardSequencePanel;
    FrontDeskStaffProfile frontDeskStaffProfile;

    public BookARoomAtHotelJPanel(Business b, FrontDeskStaffProfile fdsp, JPanel clp) {
        initComponents();
        this.business = b;
        this.frontDeskStaffProfile = fdsp;
        this.CardSequencePanel = clp;

        populateTable();

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblRooms.getModel();
        dtm.setRowCount(0);
        for (Room room : business.getHotelRoomDirectory().getRoomList()) {
            Object[] row = new Object[7];
            row[0] = room.getRoomId();
            row[1] = room.getRoomType();
            row[2] = room.getRoomPrice();
            row[3] = room.getAvailability();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnAddRoom = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRoomQT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookings = new javax.swing.JTable();
        btnConfirmBooking = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Book A Room");

        lblSubTitle1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSubTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle1.setText("View All Rooms");

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        tblRooms.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room ID", "Room Type", "Room Tariff", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        btnAddRoom.setBackground(new java.awt.Color(0, 153, 255));
        btnAddRoom.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnBack.setBackground(java.awt.Color.pink);
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter no. of rooms");

        txtRoomQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomQTActionPerformed(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        tblBookings.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tblBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Room Type", "Room Tariff", "Availability", "Guest Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBookings);

        btnConfirmBooking.setBackground(new java.awt.Color(0, 153, 255));
        btnConfirmBooking.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnConfirmBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmBooking.setText("Confirm Booking");
        btnConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBookingActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer name:");

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSubTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConfirmBooking)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRoomQT, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(115, 115, 115))))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtRoomQT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRoom))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConfirmBooking)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        FrontDeskStaffLandingPageJPanel frontDeskStaffLandingPagePanel = new FrontDeskStaffLandingPageJPanel(business, frontDeskStaffProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("HotelManagerLandingPageJPanel", frontDeskStaffLandingPagePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        if (txtRoomQT.getText().equals("") || txtRoomQT.getText() == null) {
            JOptionPane.showMessageDialog(null, "Please enter room quantity",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtCustomerName.getText().equals("") || txtCustomerName.getText() == null) {
            JOptionPane.showMessageDialog(null, "Please enter name of the customer",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int roomQty = Integer.parseInt(txtRoomQT.getText());

        int roomsTableSize = tblRooms.getRowCount();
        int selectedrow = tblRooms.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > roomsTableSize - 1) {
            JOptionPane.showMessageDialog(null, "Please select a row first",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedRoomIndex = tblRooms.getSelectedRow();
        Room selectedRoom = business.getHotelRoomDirectory().getRoomList().get(selectedRoomIndex);
        if (roomQty > selectedRoom.getAvailability()) {
            JOptionPane.showMessageDialog(null, "Rooms not available, check availability first",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }
        if (selectedRoom == null) {
            return;
        } else {
            Object[] row = new Object[5];
            row[0] = selectedRoom.getRoomId();
            row[1] = selectedRoom.getRoomType();
            row[2] = selectedRoom.getRoomPrice();
            row[3] = txtRoomQT.getText();
            row[4] = txtCustomerName.getText();
            ((DefaultTableModel) tblBookings.getModel()).addRow(row);
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void txtRoomQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomQTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomQTActionPerformed

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
        // TODO add your handling code here:
        Person customerperson = new Person(String.valueOf(business.getPersonDirectory().
                getPersonlist().size() + 1000));
        customerperson.setName(txtCustomerName.getText());
        CustomerProfile custProf1 = new CustomerProfile(customerperson);
        UserAccount custAcc1 = business.getUserAccountDirectory().newUserAccount(custProf1, customerperson.getName().toLowerCase(), customerperson.getName().toLowerCase());

        DefaultTableModel dtm = (DefaultTableModel) tblBookings.getModel();
        Object[] columnData = new Object[tblBookings.getRowCount()];  // One entry for each row
        Object[] rowData = new Object[tblBookings.getRowCount()];

        Booking booking = new Booking(String.valueOf(business.getHotelRoomBookings().getBookingList().size() + 1000), custProf1);

        for (int i = 0; i < tblBookings.getRowCount(); i++) {  // Loop through the rows

            String roomId = (String) tblBookings.getValueAt(i, 0);
            System.out.println(roomId);
            if (roomId == "" || roomId == null) {
                continue;
            }

            Room foundRoom = business.getHotelRoomDirectory().findRoom(roomId);
            booking.addRoomBooked(foundRoom, Integer.parseInt((String) tblBookings.getValueAt(i, 3)));
            foundRoom.setAvailability(foundRoom.getAvailability() - Integer.parseInt(txtRoomQT.getText()));
        }

        business.getHotelRoomBookings().addBooking(booking);
        populateTable();

    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSubTitle1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBookings;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtRoomQT;
    // End of variables declaration//GEN-END:variables
}
