/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Enterprise1.Organization1.WorkArea.HotelManager.WorkResp1;

import TheBusiness.Business.Business;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelManagerProfile;
import TheBusiness.Personnel.Profile;
import UserInterface.Enterprise1.Organization1.WorkArea.HotelManager.HotelManagerLandingPageJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aadityakasbekar
 */
public class ManageStaffJPanel extends javax.swing.JPanel {

    Business business;
    javax.swing.JPanel CardSequencePanel;
    HotelManagerProfile hotelManagerProfile;

    /**
     * Creates new form ManageStaffJPanel
     */
    public ManageStaffJPanel(Business b, HotelManagerProfile hmp, JPanel cardSequencePanel) {
        initComponents();
        business = b;
        this.hotelManagerProfile = hmp;
        this.CardSequencePanel = cardSequencePanel;
        txtStaffName.setEnabled(false);
        txtStaffGender.setEnabled(false);
        txtStaffAge.setEnabled(false);
        txtStaffContact.setEnabled(false);
        btnSave.setVisible(false);
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblHotelStaff.getModel();
        dtm.setRowCount(0);
        for (Profile hotelStaffProfile : business.getHotelStaffDirectory().getHotelStaffList()) {
            Object[] row = new Object[7];
            row[0] = hotelStaffProfile.getPerson().getPersonId();
            row[1] = hotelStaffProfile.getPerson().getName();
            row[2] = hotelStaffProfile.getPerson().getGender();
            row[3] = hotelStaffProfile.getPerson().getAge();
            row[4] = hotelStaffProfile.getPerson().getPhoneNumber();
            row[5] = hotelStaffProfile.getRole();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHotelStaff = new javax.swing.JTable();
        lblSubTitle2 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtStaffName = new javax.swing.JTextField();
        lblProductId = new javax.swing.JLabel();
        txtStaffGender = new javax.swing.JTextField();
        lblProductPrice = new javax.swing.JLabel();
        txtStaffAge = new javax.swing.JTextField();
        lblProductAvailability = new javax.swing.JLabel();
        txtStaffContact = new javax.swing.JTextField();
        btnUpdateStaffDetails = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRemoveStaff1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setMixingCutoutShape(null);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Staff");

        lblSubTitle1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSubTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle1.setText("View All Staff Members");

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        tblHotelStaff.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tblHotelStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gender", "Age", "Contact", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHotelStaff);

        lblSubTitle2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSubTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle2.setText("Add New Hotel Staff");

        lblProductName.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("Name");

        txtStaffName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffNameActionPerformed(evt);
            }
        });

        lblProductId.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProductId.setForeground(new java.awt.Color(255, 255, 255));
        lblProductId.setText("Gender");

        txtStaffGender.setEditable(false);
        txtStaffGender.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtStaffGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffGenderActionPerformed(evt);
            }
        });

        lblProductPrice.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProductPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblProductPrice.setText("Age");

        txtStaffAge.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblProductAvailability.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProductAvailability.setForeground(new java.awt.Color(255, 255, 255));
        lblProductAvailability.setText("Contact");

        txtStaffContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnUpdateStaffDetails.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdateStaffDetails.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdateStaffDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStaffDetails.setText("Update Staff Details");
        btnUpdateStaffDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffDetailsActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(java.awt.Color.pink);
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveStaff1.setBackground(new java.awt.Color(0, 153, 255));
        btnRemoveStaff1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRemoveStaff1.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveStaff1.setText("Remove Staff");
        btnRemoveStaff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStaff1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProductPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStaffAge, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSubTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblProductId)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStaffGender, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblProductName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblProductAvailability)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStaffContact, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnUpdateStaffDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSubTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductAvailability)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRemoveStaff1)
                        .addGap(46, 46, 46)
                        .addComponent(btnUpdateStaffDetails)
                        .addGap(55, 55, 55)
                        .addComponent(btnSave)))
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        HotelManagerLandingPageJPanel hotelManagerLandingPagePanel = new HotelManagerLandingPageJPanel(business, hotelManagerProfile, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("HotelManagerLandingPageJPanel", hotelManagerLandingPagePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHotelStaff.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first",
                    "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Profile staffProfile = business.getHotelStaffDirectory().getHotelStaffList().get(selectedRow);
            staffProfile.getPerson().setName(txtStaffName.getText());
            staffProfile.getPerson().setGender(txtStaffGender.getText());
            staffProfile.getPerson().setPhoneNumber(txtStaffContact.getText());
            staffProfile.getPerson().setAge(txtStaffAge.getText());

            txtStaffName.setEnabled(false);
            txtStaffGender.setEnabled(false);
            txtStaffAge.setEnabled(false);
            txtStaffContact.setEnabled(false);

            btnSave.setVisible(false);
            populateTable();
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateStaffDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffDetailsActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblHotelStaff.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first",
                    "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            btnSave.setVisible(true);
            txtStaffName.setEnabled(true);
            txtStaffGender.setEnabled(true);
            txtStaffAge.setEnabled(true);
            txtStaffContact.setEnabled(true);

            Profile staffProfile = business.getHotelStaffDirectory().getHotelStaffList().get(selectedRow);
            txtStaffName.setText(staffProfile.getPerson().getName());
            txtStaffGender.setText(staffProfile.getPerson().getGender());
            txtStaffContact.setText(staffProfile.getPerson().getPhoneNumber());
            txtStaffAge.setText(staffProfile.getPerson().getAge());

        }

    }//GEN-LAST:event_btnUpdateStaffDetailsActionPerformed

    private void btnRemoveStaff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStaff1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHotelStaff.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first",
                    "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Profile staffProfile = business.getHotelStaffDirectory().getHotelStaffList().get(selectedRow);
            business.getHotelStaffDirectory().removeStaff(staffProfile);
            populateTable();
        }


    }//GEN-LAST:event_btnRemoveStaff1ActionPerformed

    private void txtStaffGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffGenderActionPerformed

    private void txtStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveStaff1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateStaffDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductAvailability;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblSubTitle1;
    private javax.swing.JLabel lblSubTitle2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblHotelStaff;
    private javax.swing.JTextField txtStaffAge;
    private javax.swing.JTextField txtStaffContact;
    private javax.swing.JTextField txtStaffGender;
    private javax.swing.JTextField txtStaffName;
    // End of variables declaration//GEN-END:variables
}
