/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Main;


import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.EducationManagement.ProfessorProfile;
import TheBusiness.EducationManagement.StudentProfile;
import TheBusiness.Personnel.EmployeeProfile;
import TheBusiness.Personnel.Enterprise1.Organization1.FrontDeskStaffProfile;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelManagerProfile;
import TheBusiness.Personnel.Enterprise1.Organization2.SalesPersonProfile;
import TheBusiness.Personnel.Profile;
import TheBusiness.UserAccountManagement.UserAccount;
import TheBusiness.UserAccountManagement.UserAccountDirectory;
import UserInterface.Admin.AdminJPanel;
import UserInterface.Admin.ReportDashboardHotelManagementJPanel;
import UserInterface.Enterprise1.Organization1.WorkArea.FrontDeskStaff.FrontDeskStaffLandingPageJPanel;
import UserInterface.Enterprise1.Organization1.WorkArea.HotelManager.HotelManagerLandingPageJPanel;
import UserInterface.Enterprise2.Organization1.WorkArea.SalesRepresentative.WorkResp1.ManageProductsJPanel;

import UserInterface.Enterprise4.Organization1.WorkArea.Professor.ProfessorLandingPageJPanel;
import UserInterface.Enterprise4.Organization1.WorkArea.Student.StudentLandingPageJPanel;
import UserInterface.Enterprise2.Organization1.WorkArea.SalesRepresentative.SalesRepresentativeLandingPageJPanel;
import UserInterface.Enterprise3.Organization1.WorkArea.Customer.CustomerLandingPageJPanel;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Represents the main JFrame for the Hospitality Ecosystem Management System.
 * Handles user authentication, login, signUp, and navigation to different user
 * roles work areas. Manages the overall user interface and card layout.
 *
 * @author sakshiwadaskar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Reference to the Business object representing the back end system.
     */
    Business business;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        business = ConfigureABusiness.initialize();
        buttonLogOut.setVisible(false);
        System.out.println("Lets Gooo, Login or SignUp !!!");
    }
    
    // Utility method to convert a byte array to a hexadecimal string
    private static String bytesToHex(byte[] bytes) {
        StringBuilder hexString = new StringBuilder();
        for (byte b : bytes) {
            hexString.append(String.format("%02x", b));
        }
        return hexString.toString();
    }
    
    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash1 = md.digest(password.getBytes());
            String hashedPwdString = bytesToHex(hash1);
            System.out.println("Hash 1: " + hashedPwdString);
            return hashedPwdString;
        } catch (NoSuchAlgorithmException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitHomeArea = new javax.swing.JSplitPane();
        actionsidejpanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();
        CardSequencePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(1300, 700));

        actionsidejpanel.setBackground(new java.awt.Color(102, 102, 102));
        actionsidejpanel.setForeground(new java.awt.Color(255, 255, 255));
        actionsidejpanel.setMinimumSize(new java.awt.Dimension(200, 700));
        actionsidejpanel.setPreferredSize(new java.awt.Dimension(200, 700));

        btnLogin.setBackground(new java.awt.Color(0, 153, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLoginButtonActionPerformed(evt);
            }
        });

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");

        UserNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        UserNameTextField.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        UserNameTextField.setText("admin");
        UserNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        PasswordTextField.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        PasswordTextField.setText("XXXX");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        lblPassword.setBackground(new java.awt.Color(51, 51, 51));
        lblPassword.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");

        btnSignup.setBackground(new java.awt.Color(0, 153, 255));
        btnSignup.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("SignUp");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupLoginButtonActionPerformed(evt);
            }
        });

        buttonLogOut.setBackground(new java.awt.Color(0, 153, 255));
        buttonLogOut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogOut.setText("Log Out");
        buttonLogOut.setPreferredSize(new java.awt.Dimension(76, 30));
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionsidejpanelLayout = new javax.swing.GroupLayout(actionsidejpanel);
        actionsidejpanel.setLayout(actionsidejpanelLayout);
        actionsidejpanelLayout.setHorizontalGroup(
            actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsidejpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(PasswordTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionsidejpanelLayout.createSequentialGroup()
                        .addGroup(actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSignup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        actionsidejpanelLayout.setVerticalGroup(
            actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsidejpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblUsername)
                .addGap(4, 4, 4)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(buttonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SplitHomeArea.setLeftComponent(actionsidejpanel);

        CardSequencePanel.setBackground(new java.awt.Color(255, 255, 255));
        CardSequencePanel.setMinimumSize(new java.awt.Dimension(1000, 700));
        CardSequencePanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        CardSequencePanel.setLayout(new java.awt.CardLayout());

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myIcons/hotelImg4.jpeg"))); // NOI18N
        lblTitle.setText("    Hospitality Ecosystem Management System: Orchestrating Service, Education, and Operations");
        CardSequencePanel.add(lblTitle, "card2");

        SplitHomeArea.setRightComponent(CardSequencePanel);

        getContentPane().add(SplitHomeArea, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void btnLoginLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLoginButtonActionPerformed
        // TODO add your handling code here:

        if (UserNameTextField.getText().equals("") || PasswordTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Login Failed! Enter username or password is empty", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Login Failed! Enter username or password is empty");
        } else {

            String un = UserNameTextField.getText();
            //String pw = PasswordTextField.getText();
            String hashedEnteredPwd = hashPassword(PasswordTextField.getText());

            UserAccountDirectory uad = business.getUserAccountDirectory();
            UserAccount useraccount = uad.AuthenticateUser(un, hashedEnteredPwd);
            if (useraccount == null) {
                JOptionPane.showMessageDialog(this, "Invalid credentials", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Invalid credentials Entered");
                System.out.println("Try Again with Correct Credetials");
                return;
            }

            buttonLogOut.setVisible(true);
            btnLogin.setVisible(false);
            btnSignup.setVisible(false);
            UserNameTextField.setVisible(false);
            PasswordTextField.setVisible(false);
            lblUsername.setVisible(false);
            lblPassword.setVisible(false);

            String r = useraccount.getRole();
            Profile profile = useraccount.getAssociatedPersonProfile();

            if (profile instanceof HotelManagerProfile) {
                System.out.println("Loged In as Hotel Manager");
                HotelManagerProfile hotelMangerProfile = (HotelManagerProfile) profile;
                HotelManagerLandingPageJPanel hotelmanagerworkareajpanel = new HotelManagerLandingPageJPanel(business, hotelMangerProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("HotelManagerWorkAreaJPanel", hotelmanagerworkareajpanel);
                JOptionPane.showMessageDialog(this, "Logged In As Hotel Manager");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

            }

            if (profile instanceof FrontDeskStaffProfile) {
                System.out.println("Loged In as Front Desk Staff");
                FrontDeskStaffProfile fdsp = (FrontDeskStaffProfile) profile;
                FrontDeskStaffLandingPageJPanel frontDeskStaffworkareajpanel = new FrontDeskStaffLandingPageJPanel(business, fdsp, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("FrontDeskStaffLandingPageJPanel", frontDeskStaffworkareajpanel);
                JOptionPane.showMessageDialog(this, "Logged In As Front Desk Staff");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

            }

            if (profile instanceof SalesPersonProfile) {
                System.out.println("Loged In as Sales Person");
                SalesPersonProfile spp = (SalesPersonProfile) profile;
                SalesRepresentativeLandingPageJPanel salesRepresentativeworkareajpanel = new SalesRepresentativeLandingPageJPanel(business, spp, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("SalesRepresentativeLandingPageJPanel", salesRepresentativeworkareajpanel);
                JOptionPane.showMessageDialog(this, "Logged In As Sales Represntative");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

            }

            if (profile instanceof StudentProfile) {
                System.out.println("Loged In as Student");
                StudentProfile studentProfile = (StudentProfile) profile;
                StudentLandingPageJPanel studentLandingPageJPanel = new StudentLandingPageJPanel(business, studentProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("StudentLandingPageJPanel", studentLandingPageJPanel);
                JOptionPane.showMessageDialog(this, "Logged In As Student");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

            }

            if (profile instanceof ProfessorProfile) {
                System.out.println("Loged In as Professor");
                ProfessorProfile professorProfile = (ProfessorProfile) profile;
                ProfessorLandingPageJPanel professorLandingPageJPanel = new ProfessorLandingPageJPanel(business, professorProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("ProfessorLandingPageJPanel", professorLandingPageJPanel);
                JOptionPane.showMessageDialog(this, "Logged In As Faculty");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

            }
            
            if (profile instanceof CustomerProfile) {
                System.out.println("Loged In as Customer");
                CustomerProfile customerProfile = (CustomerProfile) profile;
                CustomerLandingPageJPanel customerLandingPageJPanel = new CustomerLandingPageJPanel(business, customerProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("ProfessorLandingPageJPanel", customerLandingPageJPanel);
                JOptionPane.showMessageDialog(this, "Logged In As Customer");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            }
            
            if (profile instanceof EmployeeProfile) {
                System.out.println("Loged In as Customer");
                EmployeeProfile adminProfile = (EmployeeProfile) profile;
                AdminJPanel reportPanel = new AdminJPanel(business, adminProfile, CardSequencePanel);
                CardSequencePanel.removeAll();
                CardSequencePanel.add("ReportDashboardJPanel", reportPanel);
                JOptionPane.showMessageDialog(this, "Logged In As Admin");
                ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            }
        }

    }//GEN-LAST:event_btnLoginLoginButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void btnSignupLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupLoginButtonActionPerformed
        // TODO add your handling code here:
        SignUpJPanel signUpPanel = new SignUpJPanel(business, CardSequencePanel);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("SignUpJPanel", signUpPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnSignupLoginButtonActionPerformed

    /**
     *
     * @param evt
     */
    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Logout Successfull");
        SplitHomeArea.setRightComponent(CardSequencePanel);
        buttonLogOut.setVisible(false);

        btnLogin.setVisible(true);
        btnSignup.setVisible(true);
        UserNameTextField.setVisible(true);
        PasswordTextField.setVisible(true);
        lblUsername.setVisible(true);
        lblPassword.setVisible(true);

        UserNameTextField.setText("");
        PasswordTextField.setText("");
        CardSequencePanel.removeAll();
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void UserNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequencePanel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JSplitPane SplitHomeArea;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JPanel actionsidejpanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}

// UserInterface.Enterprise1.Organization1.WorkArea.SalesRep.WorkResp1
