/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerDirectory;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.EducationManagement.ProfessorDirectory;
import TheBusiness.EducationManagement.ProfessorProfile;
import TheBusiness.EducationManagement.StudentDirectory;
import TheBusiness.EducationManagement.StudentProfile;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelStaffDirectory;
import TheBusiness.Personnel.Enterprise1.Organization1.FrontDeskStaffProfile;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelManagerDirectory;
import TheBusiness.Personnel.Enterprise1.Organization1.HotelManagerProfile;
import TheBusiness.Personnel.Enterprise1.Organization2.SalesPersonDirectory;
import TheBusiness.Personnel.Enterprise1.Organization2.SalesPersonProfile;
import TheBusiness.Personnel.Person;
import TheBusiness.Personnel.PersonDirectory;
import TheBusiness.Personnel.Profile;
import TheBusiness.UserAccountManagement.UserAccount;
import TheBusiness.UserAccountManagement.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sakshiwadaskar
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    javax.swing.JPanel CardSequencePanel;
    Business business;
//    StudentDirectory studentDir;
//    ProfessorDirectory professorDir;
//    UserAccountDirectory userAccDir;

    public SignUpJPanel(Business business, JPanel c) {
        initComponents();
        this.CardSequencePanel = c;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        roleBoxEnterprise = new javax.swing.JComboBox<>();
        lblPhoneNumber2 = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSpecialization1 = new javax.swing.JLabel();
        roleBoxOrganization = new javax.swing.JComboBox<>();
        roleBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 153, 255));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name:");

        txtUserName.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Birth:");

        txtDOB.setBackground(new java.awt.Color(204, 204, 204));

        btnCreate.setBackground(new java.awt.Color(0, 153, 255));
        btnCreate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblFullName.setBackground(new java.awt.Color(204, 204, 204));
        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("Full Name:");

        txtFullName.setBackground(new java.awt.Color(204, 204, 204));

        lblPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Phone Number:");

        txtPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));

        lblPhoneNumber1.setBackground(new java.awt.Color(204, 204, 204));
        lblPhoneNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber1.setText("Gender:");

        txtGender.setBackground(new java.awt.Color(204, 204, 204));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        roleBoxEnterprise.setBackground(new java.awt.Color(204, 204, 204));
        roleBoxEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mariott International Inc.", "Ecolab Inc." ,"Booking Holdings Inc.","Hospitality Trainings Institute"}));
        roleBoxEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleBoxEnterpriseActionPerformed(evt);
            }
        });

        lblPhoneNumber2.setBackground(new java.awt.Color(204, 204, 204));
        lblPhoneNumber2.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber2.setText("Select Enterprise:");

        lblSpecialization.setBackground(new java.awt.Color(204, 204, 204));
        lblSpecialization.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecialization.setText("Select Organization:");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up ");

        lblSpecialization1.setBackground(new java.awt.Color(204, 204, 204));
        lblSpecialization1.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecialization1.setText("Select Role:");

        roleBoxOrganization.setBackground(new java.awt.Color(204, 204, 204));
        roleBoxOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JW Mariott", "Hospitality Supplier1" ,"Booking.com","International Hotel School"}));
        roleBoxOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleBoxOrganizationActionPerformed(evt);
            }
        });

        roleBox.setBackground(new java.awt.Color(204, 204, 204));
        roleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Manager", "Front Desk Staff" ,"Sales Representative","Bookings.com Admin", "Bookings.com customer" ,"Professor", "Student"}));
        roleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPhoneNumber1)
                                .addComponent(lblPhoneNumber2)
                                .addComponent(lblSpecialization)
                                .addComponent(lblPhoneNumber)
                                .addComponent(lblSpecialization1))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roleBoxEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roleBoxOrganization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roleBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, roleBox, roleBoxEnterprise, roleBoxOrganization, txtDOB, txtFullName, txtGender, txtPassword, txtPhoneNumber, txtUserName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber1)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleBoxOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization1))
                .addGap(37, 37, 37)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, roleBoxEnterprise, txtDOB, txtFullName, txtGender, txtPassword, txtPhoneNumber, txtUserName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        if (txtUserName.getText().equals("") || txtPassword.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Signed up not successful!, please enter username/password");

        } else {
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String name = txtFullName.getText();
            String dob = txtDOB.getText();
            String gender = txtGender.getText();
            String selectEnterprise = roleBoxEnterprise.getSelectedItem().toString();
            String selectOrganization = roleBoxOrganization.getSelectedItem().toString();
            String selectRole = roleBox.getSelectedItem().toString();

            String phoneNumber = txtPhoneNumber.getText();

            PersonDirectory personDirectory = business.getPersonDirectory();
            Person person = new Person(selectRole + String.valueOf(personDirectory.getPersonlist().size() + 1));
            person.setName(name);
            person.setDateOfBirth(dob);
            person.setGender(gender);
            person.setPhoneNumber(phoneNumber);

            if (selectRole.equals("Hotel Manager")) {
                HotelManagerDirectory hotelmanagerDir = business.getHotelManagerDirectory();
                HotelManagerProfile hotelManagerProfile = hotelmanagerDir.newHotelManagerProfile(person);
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount hotelManagerUserAcc = userAccDir.newUserAccount(hotelManagerProfile, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Hotel Manager successfully!");
            }

            if (selectRole.equals("Front Desk Staff")) {
                HotelStaffDirectory hotelStaffDirecotory = business.getHotelStaffDirectory();
                Profile frontDeskStaffProfile = hotelStaffDirecotory.addNewStaff(person, "Front Desk Staff");
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount frontDeskStaffUserAcc = userAccDir.newUserAccount(frontDeskStaffProfile, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Front Desk Staff  successfully!");
            }

            if (selectRole.equals("Student")) {
//                StudentProfile studentProfile = personDirectory.newStudent(person, selectRole);
                StudentDirectory studentDir = business.getStudentdirectory();
                StudentProfile studentprofile = studentDir.newStudentProfile(person);
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount studentUserAcc = userAccDir.newUserAccount(studentprofile, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Student successfully!");
            }
            if (selectRole.equals("Professor")) {
                //   ProfessorProfile professorProfile = personDirectory.newFaculty(person, role, txtOrganization.getText());

                ProfessorDirectory facultyDir = business.getProfessorDirectory();
                ProfessorProfile professorprofile = facultyDir.newProfessorProfile(person);
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount professorUserAcc = userAccDir.newUserAccount(professorprofile, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Faculty successfully!");
            }
            if (selectRole.equals("Customer")) {
//                PersonDirectory persondirectory = business.getPersonDirectory();
//                Person customer1 = new Person(String.valueOf(persondirectory.getPersonlist().size() + 1000));
                
                Profile custProf1 = new CustomerProfile(person);
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount custAcc1 = userAccDir.newUserAccount(custProf1, "sak", "sak");
                
                UserAccount professorUserAcc = userAccDir.newUserAccount(custProf1, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Customer successfully!");
            }
            
            if (selectRole.equals("Sales Person")) {
                // ProfessorProfile professorProfile = personDirectory.newFaculty(person, role, txtOrganization.getText());

                SalesPersonDirectory salesPersonDir = business.getSalesPersondirectory();
                SalesPersonProfile salesPersonProfile = salesPersonDir.newSalesPersonProfile(person);
                UserAccountDirectory userAccDir = business.getUserAccountDirectory();
                UserAccount professorUserAcc = userAccDir.newUserAccount(salesPersonProfile, userName, password);
                JOptionPane.showMessageDialog(null, "Signed up as a Sales person successfully!");
            }

            txtUserName.setText("");
            txtPassword.setText("");
            txtFullName.setText("");
            txtDOB.setText("");
            txtGender.setText("");
            txtPhoneNumber.setText("");
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void roleBoxEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleBoxEnterpriseActionPerformed
        // TODO add your handling code here:
        
        //"Mariott International Inc.", "Ecolab Inc." ,"Booking Holdings Inc.","Hospitality Trainings Institute"}));
        if(roleBoxEnterprise.equals("Mariott International Inc.")) {
            roleBoxOrganization.addItem("JW Marriot");
        }
    }//GEN-LAST:event_roleBoxEnterpriseActionPerformed

    private void roleBoxOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleBoxOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleBoxOrganizationActionPerformed

    private void roleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblPhoneNumber2;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblSpecialization1;
    private javax.swing.JComboBox<String> roleBox;
    private javax.swing.JComboBox<String> roleBoxEnterprise;
    private javax.swing.JComboBox<String> roleBoxOrganization;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
